# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a81b83872b7479f59a656b8b4568a2220b1e934efcf98b1bd8702a218849ecfb8fdc97d7618e81418eede6984d59838250ee3751568cda8599f257ccc6bf136

test:
  secret_key_base: 2ccfdd770d8a250d3d9ea74781b37c6e8c01cc04af32be73cf368a5ccc96109aa8e1b33ccdd05ce5e5d10b18dcee119edede2a58946d0795c9266616ce004c72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
